#!/bin/bash

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  asciidoctor \
  zsh xz-utils liblz4-tool musl-tools
rustup toolchain install stable-x86_64-pc-windows-gnu
rustup default stable-x86_64-pc-windows-gnu