name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "00 01 * * *"
jobs:
  test:
    name: test
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS:
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          # Essential platform coverage - keep it simple!
          - linux
          - macos-intel
          - macos-arm
          - win-msvc
        include:
          - build: linux
            os: ubuntu-22.04
            rust: stable
          - build: macos-intel
            os: macos-13
            rust: stable
          - build: macos-arm
            os: macos-14
            rust: stable
          - build: win-msvc
            os: windows-2022
            rust: stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          bash ci/ubuntu-install-packages

      - name: Install packages (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          bash ci/macos-install-packages

      - name: Set up Python
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build tidy-viewer and all crates
        run: cargo build --verbose --workspace

      - name: Run tests
        run: cargo test --verbose --workspace
